name: Run Python Script on Schedule

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour; adjust as needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 yagmail

      - name: Run the Python script
        run: python scrap.py
